carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name="cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart, name="remove_cart"),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/',
         views.delete_cart_item, name="delete_cart_item"),

    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart"),

    path('checkout/',views.checkout,name="checkout"),
]

lcshop/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse



def health(_request):
    return HttpResponse("ok", content_type="text/plain")

urlpatterns = [
    path("health/", health, name="health"),
    path('admin/', include('admin_honeypot.urls',namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.home, name="home"),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),


    path('store/', include('store.urls')),
    path('orders/', include('orders.urls')),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.store, name='store'),
    path('submit_review/<int:product_id>/', views.submit_review, name="submit_review"),

    path('search/', views.search, name="search"),

    path('<slug:category_slug>/', views.store, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/',
         views.product_detail, name='product_detail'),



]

store/models.py
from functools import cached_property
from django.db import models
from django.urls import reverse
from accounts.models import Account
from category.models import Category
from django.db.models import Avg,Count

# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    product_description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name
    
    @cached_property
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    @cached_property
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count



class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_name='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_name='size', is_active=True)


variation_name_choice = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_name = models.CharField(
        max_length=100, choices=variation_name_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value
    



class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.subject
    

class ProductGallery(models.Model):
    product = models.ForeignKey(Product,default=None,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products',max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms

from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject','review','rating']
    

carts/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from store.models import Product, Variation
from django.contrib.auth.decorators import login_required

# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    current_user = request.user

    # ---------------------------
    # Get product variations
    # ---------------------------
    product_variation = []
    if request.method == 'POST':
        for key, value in request.POST.items():
            try:
                variation = Variation.objects.get(
                    product=product,
                    variation_name__iexact=key,
                    variation_value__iexact=value
                )
                product_variation.append(variation)
            except Variation.DoesNotExist:
                pass

    current_variation_ids = sorted([v.id for v in product_variation])

    # ==================================================
    # AUTHENTICATED USER
    # ==================================================
    if current_user.is_authenticated:
        cart_items = CartItem.objects.filter(product=product, user=current_user)

        if cart_items.exists():
            ex_var_list = []
            item_ids = []

            for item in cart_items:
                existing_variation_ids = sorted(
                    list(item.variations.values_list('id', flat=True))
                )
                ex_var_list.append(existing_variation_ids)
                item_ids.append(item.id)

            if current_variation_ids in ex_var_list:
                index = ex_var_list.index(current_variation_ids)
                item = CartItem.objects.get(id=item_ids[index])
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    user=current_user
                )
                if product_variation:
                    item.variations.add(*product_variation)
                item.save()
        else:
            item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user
            )
            if product_variation:
                item.variations.add(*product_variation)
            item.save()

        return redirect('cart')

    # ==================================================
    # GUEST USER
    # ==================================================
    else:
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))

        cart_items = CartItem.objects.filter(product=product, cart=cart)

        if cart_items.exists():
            ex_var_list = []
            item_ids = []

            for item in cart_items:
                existing_variation_ids = sorted(
                    list(item.variations.values_list('id', flat=True))
                )
                ex_var_list.append(existing_variation_ids)
                item_ids.append(item.id)

            if current_variation_ids in ex_var_list:
                index = ex_var_list.index(current_variation_ids)
                item = CartItem.objects.get(id=item_ids[index])
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    cart=cart
                )
                if product_variation:
                    item.variations.add(*product_variation)
                item.save()
        else:
            item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            if product_variation:
                item.variations.add(*product_variation)
            item.save()

        return redirect('cart')
    
           


def remove_cart(request,  product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            print('user is logged in trying to delete the item')
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def delete_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        print('user is logged in trying to delete the item')
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart= Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass #just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax'       : tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request,total=0,quantity=0,cart_items=None):
    try:
        tax=0
        grand_total = 0
        if request.user.is_authenticated:
            print('authenticated')
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
            print(cart_items)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True) 
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
        'tax':tax,
        'grand_total':grand_total,
    }

    return render(request,'orders/checkout.html',context)

store/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404

from carts.models import CartItem
from category.models import Category
from carts.views import _cart_id
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from orders.models import OrderProduct

from .forms import ReviewForm
from django.contrib import messages

from .models import Product, ProductGallery, ReviewRating

# Create your views here.


def store(request, category_slug=None):
    categories = None
    products = None
    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(
            category=categories, is_available=True)
        paginator = Paginator(products, 4)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
        for product in products:
            reviews = ReviewRating.objects.filter(product_id = product.id, status=True)
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 4)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
        for product in products:
            reviews = ReviewRating.objects.filter(product_id = product.id, status=True)

    context = {
        'products': paged_products,
        'product_count': product_count,
        'reviews': reviews,
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(
            category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(
            request), product=single_product).exists()

    except Exception as e:
        raise e
    
    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user= request.user, product_id = single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None




    # get the reviews
    reviews = ReviewRating.objects.filter(product_id = single_product.id, status=True)

    # get the product gallery images
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)


    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct':orderproduct,
        'reviews':reviews,
        'product_gallery':product_gallery,
    }
    return render(request, 'store/product_detail.html', context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by(
                '-created_date').filter(Q(product_description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()

    context = {
        'products': products,
        'product_count': product_count,
    }

    return render(request, 'store/store.html', context)


def submit_review(request,product_id):
    if request.method == 'POST':
        url = request.META.get('HTTP_REFERER')
        try:
            print('entering try block')
            reviews = ReviewRating.objects.get(user = request.user, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            if form.is_valid():
                form.save()
                messages.success(request, "Thank you! Your review has been updated.")
            else:
                print(form.errors)
                messages.error(request, "Invalid form data.")

            return redirect(url)
            
        except ReviewRating.DoesNotExist:
            print('entering except block')

            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user = request.user
                data.save()
                messages.success(request,"Thank you! Your review has been submitted")
                return redirect(url)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link href="{% static 'css/checkout.css' %}" rel="stylesheet">
<link href="{% static 'css/auth.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

{% if not cart_items %}
<div class="empty">
    <h3>Oops! Your shopping cart is empty</h3>
    <a href="{% url 'store' %}" class="btn btn-primary">Continue shopping</a>

</div>


{% else %}
<h3>Shopping cart</h3>
<div class="checkout-wrapper container">


    <div class="row g-5">

        <!-- CART ITEMS -->
        <div class="col-lg-8">
            {% for cart_item in cart_items %}
            <div class="cart-item">
                <div class="cart-item-img">
                    <img src="{{ cart_item.product.image.url }}" alt="">
                </div>

                <div class="cart-item-info">
                    <h5>{{ cart_item.product.product_name }}</h5>
                    {% if cart_item.variations.all %}
                    {% for item in cart_item.variations.all %}
                    {{ item.variation_name | capfirst }} : {{ item.variation_value | capfirst }}<br>
                    {% endfor %}
                    {% endif %}


                </div>

                <div class="cart-item-qty">
                    <h5>Quantity</h5>
                    <div class="qty-box">
                       <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}"
                            class="qty-btn text-muted text-decoration-none"><i class="fa fa-minus"></i>
                            </a>
                        <div class="qty-value">{{ cart_item.quantity }}</div>
                        <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                            {% csrf_token %}
                            {% for item in cart_item.variations.all %}
                            <input type="hidden" name="{{ item.variation_name}}" value="{{ item.variation_value}}">
                            {% endfor %}
                            <button type="submit" class="qty-btn text-muted text-decoration-none">
                                <i class="fa fa-plus"></i></button>
                        </form>
                    </div>
                </div>

                <div class="cart-item-price">
                    <h5>Price</h5>
                    <strong> {{ cart_item.sub_total }}</strong><br>
                    <small>£ {{ cart_item.product.price }}each</small>
                </div>

                <a href="{% url 'delete_cart_item' cart_item.product.id cart_item.id %}"
                    onclick="return confirm('Are you sure you want to remove the item?')"
                    class=" btn brown-btn text-light text-decoration-none">Remove
                    <i class="fa fa-trash"></i>
                </a>
            </div>
            {% endfor %}
        </div>


        <!-- CHECKOUT SUMMARY -->
        <div class="col-lg-4">
            <div class="checkout-summary">
                <h5>Order Summary</h5>

                <div class="summary-row">
                    <span>Total Price</span>
                    <span>£ {{ total }}</span>
                </div>

                <div class="summary-row">
                    <span>Tax</span>
                    <span>£{{ tax }}</span>
                </div>

                <div class="summary-row total">
                    <span>Grand Total</span>
                    <span>£ {{ grand_total }}</span>
                </div>

                <hr>

                <div class="payment-icons">
                    <i class="fa-brands fa-cc-visa" style="color: blue;"></i>
                    <i class="fa-brands fa-cc-mastercard" style="color: rgb(255, 0, 30); "></i>
                    <i class="fa-brands fa-cc-paypal" style="color: rgba(0, 0, 255, 0.658); "></i>
                    <i class="fa-brands fa-google-pay" style="color: rgb(23, 110, 15);"></i>
                </div>

                <a href="{% url 'checkout' %}" class="btn brown-btn mt-3 text-light w-100 text-decoration-none" >Checkout</a>
                <a href="{% url 'store' %}" class="btn text-dark text-decoration-none mt-2"
                    style="background-color: rgb(231, 220, 209); width: 100%; ">Continue
                    shopping</a>
            </div>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link href="{% static 'css/product.css' %}" rel="stylesheet">
<link href="{% static 'css/star.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

{% endblock %}


{% block content%}

<div class="container mt-5">
    <div class="product_container">
        <div class="image_side p-2">
            <img  id="mainImage" src="{{ single_product.image.url }}">
            <ul class="thumb">
                {% for i in product_gallery %}
                <li>
                    <a href="{{ i.image.url }}">
                        <img src="{{ i.image.url }}" alt="Product image">
                    </a>
                </li>
                {% endfor %}
            </ul>
            
        </div>

        


        <div class=" details_side">
            <h3>{{ single_product.product_name}}</h3>
            <div class="rating-star mb-2">
                <i class="{% if single_product.averageReview >= 1 %}fa-solid fa-star{% elif single_product.averageReview >= 0.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
        
                <i class="{% if single_product.averageReview >= 2 %}fa-solid fa-star{% elif single_product.averageReview >= 1.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
        
                <i class="{% if single_product.averageReview >= 3 %}fa-solid fa-star{% elif single_product.averageReview >= 2.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
        
                <i class="{% if single_product.averageReview >= 4 %}fa-solid fa-star{% elif single_product.averageReview >= 3.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
        
                <i class="{% if single_product.averageReview >= 5 %}fa-solid fa-star{% elif single_product.averageReview >= 4.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
        
                <span>
                    
                    ({{ single_product.countReview }} reviews)
                </span>
                </div>
            <h4>£ {{single_product.price}} </h4>



            
            <p>{{ single_product.product_description }}</p>

            <form action="{% url 'add_cart' single_product.id %}" method="POST" class="form-group">
                {% csrf_token %}
                <b>Select size</b> <select class="form-control" style="width: 40%;" name="size">
                    <option>Select size</option>
                    {% for i in single_product.variation_set.sizes %}
                    <option value="{{ i.variation_value  }}">{{ i.variation_value }}</option>
                    {% endfor %}

                </select>
                <b>Select colour</b> <select class="form-control" name="color" style="width: 40%;">
                    <option>Select colour</option>
                    {% for i in single_product.variation_set.colors %}
                    <option value="{{ i.variation_value }}">{{ i.variation_value }}</option>
                    {% endfor %}
                </select>


                {% if single_product.stock <= 0 %} <h5 style="color:red; margin-top:2px;">Out of stock </h5>



                    {% else %}

                    <button type="submit" class="btn btn-primary   mt-5 mx-5">Add to cart
                        <i class="fa-solid fa-cart-shopping"></i></button>
                    {% endif %}

            </form>

        </div>
    </div>

</div>


<!-- review writing section -->

<div class="container">

    <h5>Write your review</h5>
    <form action="{% url 'submit_review' single_product.id %}" method="POST" class="form-group">
        {% csrf_token %}
        How do you rate this product?
        <br>
        <div class="rate">
            <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
            <input type="radio" name="rating" id="rating9" value="4.5"><label for="rating9" title="4.5"></label>
          
            <input type="radio" name="rating" id="rating8" value="4"><label for="rating8" title="4"></label>
            <input type="radio" name="rating" id="rating7" value="3.5"><label for="rating7" title="3.5"></label>
          
            <input type="radio" name="rating" id="rating6" value="3"><label for="rating6" title="3"></label>
            <input type="radio" name="rating" id="rating5" value="2.5"><label for="rating5" title="2.5"></label>
          
            <input type="radio" name="rating" id="rating4" value="2"><label for="rating4" title="2"></label>
            <input type="radio" name="rating" id="rating3" value="1.5"><label for="rating3" title="1.5"></label>
          
            <input type="radio" name="rating" id="rating2" value="1"><label for="rating2" title="1"></label>
            <input type="radio" name="rating" id="rating1" value="0.5"><label for="rating1" title="0.5"></label>
          
            <span class="stars" aria-hidden="true"></span>
          </div>
          
          
            
        <br>

    
        <label style="color: black;">Enter review title</label><input type="text" style="width: 80%;" name="subject" class="form-control">
        <label style="color: black;">Enter your review </label><textarea rows="3" style="width: 80%;" name="review" class="form-control"></textarea>
       
        {% if user.is_authenticated %}
            {% if orderproduct %}
                <button class="btn review-btn" type="submit">Submit Review</button>
            {% else %}
            <p>You must purchase the item  to post a review.</p>


            {% endif %}
        {% else %}
             <p>You must be logged in to post a review.<a href="{% url 'login' %}">Login</a></p>
        {% endif %}
        {% include 'alerts.html' %}
    </form>
<hr>


<!-- customer review section -->
    <div>
        <h4>Customer Reviews</h4>
        {% if reviews %}
    
        

        <div class="rating-star mb-2">
        <i class="{% if single_product.averageReview >= 1 %}fa-solid fa-star{% elif single_product.averageReview >= 0.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>

        <i class="{% if single_product.averageReview >= 2 %}fa-solid fa-star{% elif single_product.averageReview >= 1.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>

        <i class="{% if single_product.averageReview >= 3 %}fa-solid fa-star{% elif single_product.averageReview >= 2.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>

        <i class="{% if single_product.averageReview >= 4 %}fa-solid fa-star{% elif single_product.averageReview >= 3.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>

        <i class="{% if single_product.averageReview >= 5 %}fa-solid fa-star{% elif single_product.averageReview >= 4.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>

        <span>
            {{ single_product.averageReview|floatformat:1 }} / 5
            ({{ single_product.countReview }} reviews)
        </span>
        </div>

        <div class="card review-card">
        <div class="card-body">
            {% for review in reviews %}
            <div class="row">
                <div class="col-9">
                <h5 class="mb-0">{{ review.user.full_name }}</h5>
                </div>
                <div class="col-3 text-end">
                <h6>{{ review.updated_at }}</h6>
                </div>
            </div>

            <div class="rating-star mb-1">
                <i class="{% if review.rating >= 1 %}fa-solid fa-star{% elif review.rating >= 0.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
                <i class="{% if review.rating >= 2 %}fa-solid fa-star{% elif review.rating >= 1.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
                <i class="{% if review.rating >= 3 %}fa-solid fa-star{% elif review.rating >= 2.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
                <i class="{% if review.rating >= 4 %}fa-solid fa-star{% elif review.rating >= 3.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
                <i class="{% if review.rating >= 5 %}fa-solid fa-star{% elif review.rating >= 4.5 %}fa-solid fa-star-half-stroke{% else %}fa-regular fa-star{% endif %}"></i>
            </div>

            <strong>{{ review.subject }}</strong>
            <p class="mb-0">{{ review.review }}</p>
            <hr>
            {% endfor %}
        </div>
        </div>

        </div>
        {% else %}
        <p>No reviews available!</p>
        {% endif %}
    </div>

</div>





{% endblock %}